/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.astradd.view;

import javax.swing.JOptionPane;
import br.com.astradd.view.Cadastro_pedidoVIEW;
import br.com.astradd.dto.LoginDTO;
/**
 *
 * @author darry
 */
public class Tela_PrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    public Tela_PrincipalVIEW() {
        LoginDTO loginDTO = new LoginDTO();
        initComponents();
        this.setTitle("AstraDD");
        if(loginDTO.control_user.equalsIgnoreCase("adm")){
        fileMenu_adm.setEnabled(true);
        fileMenu_bio.setEnabled(true);
        fileMenu_med.setEnabled(true);
        }
        else{
            if(loginDTO.control_user.equalsIgnoreCase("fun")){
            fileMenu_adm.setEnabled(false);
            fileMenu_bio.setEnabled(true);
            fileMenu_med.setEnabled(false);
            }
            else{
            fileMenu_adm.setEnabled(false);
            fileMenu_bio.setEnabled(false);
            fileMenu_med.setEnabled(true);
            }
        }
    }
    private void sair(){
        Object[] options={"sair","cancelar"};
    if(JOptionPane.showOptionDialog(null, "deseja sair","informação",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE,null,options, options[0])==0)
      System.exit(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu_adm = new javax.swing.JMenu();
        Cadastrar_funcionario = new javax.swing.JMenuItem();
        Cadastrar_exame = new javax.swing.JMenuItem();
        fileMenu_bio = new javax.swing.JMenu();
        Responder_pedido = new javax.swing.JMenuItem();
        Pedidos = new javax.swing.JMenuItem();
        fileMenu_med = new javax.swing.JMenu();
        cadastrar_paciente = new javax.swing.JMenuItem();
        Fazer_pedido = new javax.swing.JMenuItem();
        laudo = new javax.swing.JMenuItem();
        associar_medico = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        sair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(0, 0, 0));
        desktopPane.setPreferredSize(new java.awt.Dimension(1920, 1080));

        fileMenu_adm.setMnemonic('f');
        fileMenu_adm.setText("Administrador");

        Cadastrar_funcionario.setMnemonic('o');
        Cadastrar_funcionario.setText("Cadastro de funcionário");
        Cadastrar_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_funcionarioActionPerformed(evt);
            }
        });
        fileMenu_adm.add(Cadastrar_funcionario);

        Cadastrar_exame.setMnemonic('a');
        Cadastrar_exame.setText("Cadastrar exame");
        Cadastrar_exame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_exameActionPerformed(evt);
            }
        });
        fileMenu_adm.add(Cadastrar_exame);

        menuBar.add(fileMenu_adm);

        fileMenu_bio.setMnemonic('e');
        fileMenu_bio.setText("Biomédico");

        Responder_pedido.setMnemonic('t');
        Responder_pedido.setText("Responder pedido");
        Responder_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Responder_pedidoActionPerformed(evt);
            }
        });
        fileMenu_bio.add(Responder_pedido);

        Pedidos.setText("Pedidos pendentes");
        Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidosActionPerformed(evt);
            }
        });
        fileMenu_bio.add(Pedidos);

        menuBar.add(fileMenu_bio);

        fileMenu_med.setText("Médico");

        cadastrar_paciente.setText("Cadastrar paciente");
        cadastrar_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_pacienteActionPerformed(evt);
            }
        });
        fileMenu_med.add(cadastrar_paciente);

        Fazer_pedido.setText("Fazer pedido");
        Fazer_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fazer_pedidoActionPerformed(evt);
            }
        });
        fileMenu_med.add(Fazer_pedido);

        laudo.setText("Ver laudo");
        laudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laudoActionPerformed(evt);
            }
        });
        fileMenu_med.add(laudo);

        associar_medico.setText("Associar médico");
        associar_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associar_medicoActionPerformed(evt);
            }
        });
        fileMenu_med.add(associar_medico);

        menuBar.add(fileMenu_med);

        jMenu6.setText("Opções");

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenu6.add(sair);

        menuBar.add(jMenu6);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cadastrar_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_funcionarioActionPerformed
        Cadastro_funcionarioVIEW cadastro_funcionarioVIEW = new Cadastro_funcionarioVIEW();
        this.desktopPane.add(cadastro_funcionarioVIEW);
        cadastro_funcionarioVIEW.setVisible(true);
    }//GEN-LAST:event_Cadastrar_funcionarioActionPerformed

    private void Cadastrar_exameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_exameActionPerformed
        Cadastro_exameVIEW cadastro_exameVIEW = new Cadastro_exameVIEW();
        this.desktopPane.add(cadastro_exameVIEW);
        cadastro_exameVIEW.setVisible(true);
    }//GEN-LAST:event_Cadastrar_exameActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        this.sair();
    }//GEN-LAST:event_sairActionPerformed

    private void Responder_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Responder_pedidoActionPerformed
        Responder_laudoVIEW responder_laudoVIEW = new Responder_laudoVIEW();
        this.desktopPane.add(responder_laudoVIEW);
        responder_laudoVIEW.setVisible(true);
    }//GEN-LAST:event_Responder_pedidoActionPerformed

    private void PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidosActionPerformed
        PedidosVIEW pedidosVIEW = new PedidosVIEW();
        this.desktopPane.add(pedidosVIEW);
        pedidosVIEW.setVisible(true);
    }//GEN-LAST:event_PedidosActionPerformed

    private void cadastrar_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_pacienteActionPerformed
        Cadastro_pacienteVIEW cadastro_pacienteVIEW = new Cadastro_pacienteVIEW();
        this.desktopPane.add(cadastro_pacienteVIEW);
        cadastro_pacienteVIEW.setVisible(true);
    }//GEN-LAST:event_cadastrar_pacienteActionPerformed

    private void Fazer_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fazer_pedidoActionPerformed
        Cadastro_pedidoVIEW cadastro_pedidoVIEW = new Cadastro_pedidoVIEW();
        this.desktopPane.add(cadastro_pedidoVIEW);
        cadastro_pedidoVIEW.setVisible(true);
    }//GEN-LAST:event_Fazer_pedidoActionPerformed

    private void associar_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associar_medicoActionPerformed
        Associar_medicoVIEW associar_medicoVIEW = new Associar_medicoVIEW();
        this.desktopPane.add(associar_medicoVIEW);
        associar_medicoVIEW.setVisible(true);
    }//GEN-LAST:event_associar_medicoActionPerformed

    private void laudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laudoActionPerformed
        LaudoVIEW laudoVIEW = new LaudoVIEW();
        this.desktopPane.add(laudoVIEW);
        laudoVIEW.setVisible(true);
    }//GEN-LAST:event_laudoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void Tela_Principal(){
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Tela_PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Tela_PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Tela_PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Tela_PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Tela_PrincipalVIEW().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cadastrar_exame;
    private javax.swing.JMenuItem Cadastrar_funcionario;
    private javax.swing.JMenuItem Fazer_pedido;
    private javax.swing.JMenuItem Pedidos;
    private javax.swing.JMenuItem Responder_pedido;
    private javax.swing.JMenuItem associar_medico;
    private javax.swing.JMenuItem cadastrar_paciente;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu_adm;
    private javax.swing.JMenu fileMenu_bio;
    private javax.swing.JMenu fileMenu_med;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem laudo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem sair;
    // End of variables declaration//GEN-END:variables

}
